const tutors = ref([
  {
    id: 1,
    name: "Budi Santoso",
    subject: "Matematika",
    level: "SMP & SMA",
    rating: 4.9,
    reviews: 225,
    photo: "https://picsum.photos/seed/tutor1/80/80",
    whatsapp: "+628123456789",
    bio: "Tutor Matematika bersertifikat, berpengalaman lebih dari 6 tahun mengajar siswa SMP & SMA.",
  },
  {
    id: 2,
    name: "Siti Nurhaliza",
    subject: "Fisika",
    level: "SMA",
    rating: 4.8,
    reviews: 190,
    photo: "https://picsum.photos/seed/tutor2/80/80",
    whatsapp: "081234567880",
    bio: "Ahli Fisika dengan pendekatan praktis. Fokus pada pemahaman konsep dan latihan soal berjenjang.",
  },
  {
    id: 3,
    name: "Ahmad Fauzi",
    subject: "Kimia",
    level: "SMA",
    rating: 4.8,
    reviews: 174,
    photo: "https://picsum.photos/seed/tutor3/80/80",
    whatsapp: "628111223344",
    bio: "Berpengalaman olimpiade Kimia, membimbing banyak siswa lolos PTN favorit.",
  },
  {
    id: 4,
    name: "Rina Wijaya",
    subject: "Biologi",
    level: "SMP",
    rating: 4.7,
    reviews: 130,
    photo: "https://picsum.photos/seed/tutor4/80/80",
    whatsapp: "+62 811-7777-999",
    bio: "Metode belajar interaktif dengan visual dan eksperimen sederhana.",
  },
  {
    id: 5,
    name: "Dedi Kurniawan",
    subject: "Bahasa Inggris",
    level: "SD, SMP & SMA",
    rating: 4.6,
    reviews: 125,
    photo: "https://picsum.photos/seed/t5/80/80",
    teachingMode: ["offline"],
  },
  {
    id: 6,
    name: "Maya Kartika",
    subject: "Ekonomi",
    level: "SMA",
    rating: 4.6,
    reviews: 118,
    photo: "https://picsum.photos/seed/t6/80/80",
    teachingMode: ["online", "offline"],
  },
]);